### PR TITLE
Release

### PR DESCRIPTION
**Pull request by marcelgarus**
Hey Rahiche,

I rewrote the code. Now, a custom builder is accepted which is called for every character.
Also, only one focus node and EditableText is used internally, so stuff like swiping on the space bar to change focus or holding the back button for deletion of everything works.
Just run the example app which is now included and you'll see how it works. [Here's a video of it.](https://photos.app.goo.gl/eNZdRLSWtT17z5nj8)

Because these are breaking changes, I bumped the version to 1.0.0, so library users won't break their app if they specified the version with `xxx^`.

I also added an example, cleaned the API reference and improved a lot of other stuff like the pubspec, readme and license.
The video of the widget still has to be updated tho.

Happy weekend
   Marcel

### CODE REVIEW

**Comment by Rahiche** [comment]
Great work thanks for your contribution marc

**Comment by Rahiche** [comment]
also one more think if you can add the GIF version and not the video so we can share it with other 
thanks

**Comment by marcelgarus** [comment]
Yeah, sorry about that. My internet is limited here, so could you take care of that?
And remember to publish it to the Dart pub afterward so the changes are applicable.

**Comment by Rahiche** [comment]
okay i will do that when i get home
thanks

**Pull request merged**
